### ISSUE TITLE
Track cuts off near the end consistently

### ISSUE THREAD

**Issue by thatonearchguy** [arnesongit/plugin.audio.tidal2#10]
Hello,
First of all thank you so much for making this addon, and the fix for the ffmpeg delay on Windows is much appreciated!
I've noticed a strange issue where the last minute or so of each song will get cut off, can't figure out why. 
Some help would be appreciated with this :)

**Comment by arnesongit** [comment]
Please try to deactivate the setting "Use inputstream.ffmpegdirect as default player".

**Comment by thatonearchguy** [comment]
Thanks that seems to have fixed it, not sure why that setting would relate to the last minute of playback because it's still using the ffmpegdirect backend for Tidal FLAC right?
One other niggle is that in the queue the actual name of the track doesn't appear, just the TIDAL track ID(?) - any way around this?
Edit - this has also fixed the issue where it cut the first second or two of the track :))

**Comment by thatonearchguy** [comment]
There's another issue where the track will pause once for maybe 5-10 seconds before it starts playing again - not sure why this is. Our internet is excellent so this is not the issue.

**Comment by arnesongit** [comment]
Look into the Kodi log file to see what playback engine is used !
Which device type do you have selected from the tidal.apk file ?
The inputstream addons are only für MPEG Dash streams.
If you use an "Automotive" device type, all streams should be https streams which should be playable from kodi itself.
I'm using the "Tv Non Drm Dolby Atmos" device from an older tidal apk version 2.36.2.
The delay of 5-10 seconds before starts playing is a problem with the TIDAL servers. Sometimes they are overloaded and it takes a frew seconds until the stream content is sent.

**Comment by thatonearchguy** [comment]
I'm using Automotive device type yes
I didn't mean the delay at the start, sometimes it cuts out in the middle of the song
Do you have solution for the track names coming in the Kodi queue?

Edit - decoder appears to be CDVDDemuxFFmpeg from what I could decipher from logs

**Comment by arnesongit** [comment]
There is a setting called "Set playback informations for Web-GUI". Perhaps this sets also the infos for the playback queue.

**Comment by thatonearchguy** [comment]
Thanks that's solved the playback queue :)
Do you have a solution for the track cutting in between?

**Comment by arnesongit** [comment]
Perhaps the data transfer stucks during playback.
Pleas try to tune your buffers in the advancedsettings.xml like described here: https://github.com/arnesongit/plugin.audio.tidal2/issues/5
