### ISSUE TITLE
Kodi 17.6

### ISSUE THREAD

**Issue by barkebrak** [arnesongit/plugin.audio.tidal2#10]
I had kodi setup and working perfectly with my meridian explorer 2 and tidal mqa. But suddenly it doesn't work anymore. I've checked all settings i can think of. Running kxstudio linux with alsa. I suspect it has to do with kodi update but not sure... Everything but mqa works...
Regards
Jörgen

**Comment by arnesongit** [comment]
I had the same problem a while ago (no MQA blue LED on my Meridian Explorer 2). After logout and login everything was fine again. It seems that the login session ID was too old.
Regards
arneson

**Comment by barkebrak** [comment]
Ok. Thanks

Skickat från min Windows 10-telefon

Från: arnesongit
Skickat: den 23 januari 2018 15:49
Till: arnesongit/plugin.audio.tidal2
Kopia: barkebrak; Author
Ämne: Re: [arnesongit/plugin.audio.tidal2] Kodi 17.6 (#10)

I had the same problem a while ago (no MQA blue LED on my Meridian Explorer 2). After logout and login everything was fine again. It seems that the login session ID was too old.
Regards
arneson
