### ISSUE TITLE
Plugin broken since yesterday (17.6)

### ISSUE THREAD

**Issue by weberan** [arnesongit/plugin.audio.tidal2#11]
On my two kodi (libreelec) installations the plugin is broken since yesterday:

Any command results in something like this:

`XBMC JSON-RPC Error: Invalid params.
(Code: -32602)
Data: (null)

METHOD
Files.GetDirectory

PARAMETERS
{directory="plugin://plugin.audio.tidal2/category/genres";"file_properties"=(thumbnail);media=music;sort={ignorearticle=0;method=none;order=ascending;};}

`

Anybody sees a similar behavior?

**Comment by kec2** [comment]
I just tried on the latest version of Libreelec 8.2.3. I have no problems.
Have you tried to log out and then in again of Tidal?

**Comment by weberan** [comment]
A logout and login did the job, thanks. I am using Kodi Headless for Audio only, so I did not get the message. Thanks so much, Andreas
