### ISSUE TITLE
No center speaker audio

### ISSUE THREAD

**Issue by luckylukz02** [arnesongit/plugin.audio.tidal2#13]
I made a chance discovery today. I had to remove my surround speakers for redecorating and have just the center hooked up. When I play music through the app there is no audio from the centre speaker.

It's something I should have picked up before.

To test I hooked up one of my surround speakers and there was audio. I'm guessing this is all channel surround coming from the app.

Movie audio from other applications play in surround.

**Comment by nasawyer7** [comment]
enable stereo upmix in kodi settings, or in your receiver settings if you have a setting like that.
