### ISSUE TITLE
How to install for Kodi 20?

### ISSUE THREAD

**Issue by jbrepogmailcom** [arnesongit/plugin.audio.tidal2#16]
Any advice please?

**Comment by arnesongit** [comment]
Install my repository from this zip: https://github.com/arnesongit/repository.tidal2/blob/main/repository.tidal2/repository.tidal2-0.2.1.zip?raw=true
Then install TIDAL2 from this repository.

**Comment by kec2** [comment]
@arnesongit would you please update the readme file because that points to version 0.2.0?
