### ISSUE TITLE
Tidal fatal error

### ISSUE THREAD

**Issue by Tecko71** [arnesongit/plugin.audio.tidal2#17]
I got a fatal error message all the time: Fatal error; routing error; can not find path fanart. How to fix this?

**Comment by Tecko71** [comment]
find solution I think

**Comment by arnesongit** [comment]
There are some artists where no fanart is available. Because the fanart url is dynamically build with the artist id, the addon can't check if a picture is available or not. So Kodi logs an error if a fanart url is not available.

**Comment by arnesongit** [comment]
Please can you post the part of the kodi.log where the dump is shown, so that I can look for the reason ?
Only the part of the dump, not the complete log file!
