### ISSUE TITLE
Play HLS vs inputstream.ffmpegdirect

### ISSUE THREAD

**Issue by WohnW** [arnesongit/plugin.audio.tidal2#18]
Hi
@arnesongit 
Could you please explain what is the difference between use HLS vs inputstream.ffmpegdirect ? In the perspective of audio quality?
I have Tidal HiFi Plus subscription and would be happy to get max playback quality out of this. 
![image](https://github.com/arnesongit/plugin.audio.tidal2/assets/34268821/2acd3003-f0c7-4b6c-bc97-f58bdfed63dc)

**Comment by arnesongit** [comment]
If you use a non-automotive Client-ID like FireTV the streams in Lossless+High+Low quality modes use MPD streaming (MPEG-Dash). This kind of stream can be played with the inputstream.ffmpegdirect addon.
If this addon is not available on your Kodi platform, you can try the "Play as HLS" mode. This uses my own MPEG-Dash-to-HLS stream converter which is a part of the TIDAL2 addon. This one is not as stable as ffmpegdirect and it doesn't support searching inside the stream.
The Master/MQA playback uses HTTPS streaming with all Client-IDs, so no inputstream addon is necessary to play them.

**Comment by WohnW** [comment]
> If you use a non-automotive Client-ID like FireTV the streams in Lossless+High+Low quality modes use MPD streaming (MPEG-Dash). This kind of stream can be played with the inputstream.ffmpegdirect addon. If this addon is not available on your Kodi platform, you can try the "Play as HLS" mode. This uses my own MPEG-Dash-to-HLS stream converter which is a part of the TIDAL2 addon. This one is not as stable as ffmpegdirect and it doesn't support searching inside the stream. The Master/MQA playback uses HTTPS streaming with all Client-IDs, so no inputstream addon is necessary to play them.

@arnesongit  - actually I use platform": "Android Auto" with credentials as below (found it on: https://github.com/yaronzz/Tidal-Media-Downloader/blob/master/TIDALDL-PY/tidal_dl/apiKey.py. Is it OK? Will it supply me with HiFi and Master? Author claims it does...
            "formats": "Normal/High/HiFi/Master",
            "clientId": "zU4XHVVkc2tDPo4t",
            "clientSecret": "VJKhDFqJPqvsPVNBV6ukXTJmwlvbttP7wlMlrc72se4="

In this configuration **BOTH** - HLS and inputstream.ffmpegdirect works, however HLS is significantly slower in operation and whole addon is little lagging (on i7+16Gb ram :) )

**MAY I ASSUME THAT IN THIS CASE IT DOESN'T MATTER which method I use for sound quality?**

**Comment by arnesongit** [comment]
The HLS mode is only for fallback when ffmpegdirect is not available, for instance on old Kodi 17 platforms.
And please: Do not post any client credentials because this are internal secrets of the TIDAL platform !

**Comment by WohnW** [comment]
> The HLS mode is only for fallback when ffmpegdirect is not available, for instance on old Kodi 17 platforms. And please: Do not post any client credentials because this are internal secrets of the TIDAL platform !

"internal secrets of the TIDAL platform" - sorry. I thought since it is publicly available in internet it's rather no secret :):)
