### ISSUE TITLE
Doesn't play Atmos tracks

### ISSUE THREAD

**Issue by HomerJau** [arnesongit/plugin.audio.tidal2#21]
I installed latest version today and it won't play any of the Tidal Atmos encoded tracks. The Kodi screen flickers a few times then a message saying Error 401 Asset is not ready for playback.

Anyone tried Atmos tracks?

**Comment by Harrak2** [comment]
I installed v. 1.00 20 beta. Atmos doesn't work (nvidia shield 2017, soundbar dolby atmos samsung hnw950). I can play films on kodi in dolby atmos, but Tidal Atmos Music doesn't work.
