### ISSUE TITLE
No Master Quality available, only ALAC 16/44 with TIDAL2 plugin (Kodi 18.5) with Premium Account

### ISSUE THREAD

**Issue by SmoothR81** [arnesongit/plugin.audio.tidal2#23]
I have to log out regarding a problem that a I had. I tried to log in and did not have the possiblity to get Master Quality back.
I know this issue a few months ago, Tidal changed something and you Arneson get it back to work! Please be so kind and clear this issue. Thank you very much in advance!

**Comment by cedouic** [comment]
:(

Hi, I got the same problem, I am on CoreElec 9.2.3 (Kodi 18.7.1) and I cannot get MQA...

Just reporting and hope the dev is still around.
Thanks for the work, I am using it everyday even without MQA.

**Comment by gaelblet** [comment]
Hi,

Same problem for me, when I select FLAC/MQA, I get ALAC on Libreelec 9.2.6 on RPi3.
