### ISSUE TITLE
HiRes limited to 24bit/48khz

### ISSUE THREAD

**Issue by PROVRS** [arnesongit/plugin.audio.tidal2#24]
Hello,

First of all great job keeping this plugin alive!

Is there a way to unlock the limit of HiRes FLAC track to 24/192?
I'm trying Tidal HiRes tracks which are higher than that bitrate (24/48), but they are played only up to 24/48. Tried different options from addon settings with no success.
My Coreelec Odroid N2 plays fine offline FLACs up to 24/192.

**Comment by arnesongit** [comment]
Good news: It's allready working in my development environment !
Bad news: I have to test it on several platforms, so it will take a while until all is running stable.

**Comment by PROVRS** [comment]
Still good news to me!
Thanks a lot man 💯

**Comment by arnesongit** [comment]
V2.1.3 is now able to play HiRes FLAC up to 192 kHz !
