### ISSUE TITLE
Kodi 19 compatibility

### ISSUE THREAD

**Issue by ghost** [arnesongit/plugin.audio.tidal2#24]
Can You update your addon from python2 to python3 to make it works with Kodi 19 Matrix?

**Comment by godsic** [comment]
@barqqlsky Please check my Kodi 19 port [here](https://github.com/godsic/plugin.audio.tidal2). I've made a pull request, so hopefully its going to be considered.

**Comment by olosz** [comment]
I'm trying to install the plugin from v19 repository but if fails on OSMC Matrix - it throws an error "Add-on 'plugin.audio.tidal2' is not compatible with Kodi". Is it not compatible with the OSMC?

**Comment by xv1nx** [comment]
unfortunately the problem still remains. I am trying to install tidal Addon on Kodi 19.10 but got the error:
xvmc.python in version 2.14.0 can not be resolved.
I tried the linked zip File from the main document page and also the 2.0.2 and 2.0.3 version from here:
https://github.com/arnesongit/repository.tidal2/tree/main/plugin.audio.tidal2

No luck so far.
