### ISSUE TITLE
Audio only in videos, RPi4 running LibreELEC 9.2.6

### ISSUE THREAD

**Issue by cactusero** [arnesongit/plugin.audio.tidal2#25]
I can't make the videos work in my rpi4 running libreelec, it treats them as if they were audio tracks. any idea? I think it is related to the format of the videos (mp4) but I haven't found a way to solve it. Thanks in advance!

**Comment by gaelblet** [comment]
Hello,

Same problem for me if I select FLAC 16 bit for streaming option. 
Work around, video works with default settings, ALAC or FLAC/MQA.
Unfortunately with ALAC16 the sound is very bad for me, and with FLAC/MQA, as reported in another issue, it keeps playing ALAC files instead of FLAC or MQA.
