### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by reezmaize** [arnesongit/plugin.audio.tidal2#28]
Have entered username and password, and set country code as 'UK'

`21:11:35 T:2823902272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 1] _ssl.c:504: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol`

However, the add-on runs in trial mode

**Comment by Collectiony-1** [comment]
Similar issue here. It looks like Tidal has changed the login procedure. I get an email from Tidal suggesting I'm using an old app to login (but this is triggered by the Tidal2 login attempt):

_It looks like you're using an older version of the TIDAL app on one or more of your devices.

Please update to the latest version of the app from your App Store on all your devices to continue listening to your favorite music. Please note that the TIDAL app only works on iOS 11 and higher.

We regularly update the TIDAL app to improve your streaming experience.
Please make sure you have the latest version on your devices to get the best listening experience._

**Comment by piotrek17** [comment]
I have a similar problem. I get an error when logging in.
I am from Poland, what country code should I enter?

**Comment by thewoza** [comment]
Unable to login also

```
ERROR <general>: [TIDAL2] Client not found
2021-04-19 15:09:41.827 T:9366    ERROR <general>: [TIDAL2] Forbidden
2021-04-19 15:09:43.192 T:9366    ERROR <general>: [TIDAL2] Client not found
2021-04-19 15:09:44.645 T:9366    ERROR <general>: Skipped 1 duplicate messages..
2021-04-19 15:09:44.645 T:9366    ERROR <general>: [TIDAL2] Forbidden
2021-04-19 15:09:45.824 T:9366    ERROR <general>: [TIDAL2] Client not found
```

**Comment by fischcode** [comment]
I experience the same problem:
Had a working tidal2 installation on kodi 18 until a week ago; now login fails, even with newest tidal2 version 2.0.1. Password has not changed. Kodi Log contains numerous entries of the following kind:
NOTICE: [TIDAL2] Using Token with clientUniqueKey "4eb0a135f3e337ce"
ERROR: [TIDAL2] Client not found
Tidal Login in Windows Store app works fine.

**Comment by hellofword** [comment]
The problem is not in the add-on, Tidal has limited the use to the devices it supports, see their website.

**Comment by formidabilus** [comment]
> The problem is not in the add-on, Tidal has limited the use to the devices it supports, see their website.


So, now it's not working for anyone? Will it be fixed?

**Comment by mossywell** [comment]
> The problem is not in the add-on, Tidal has limited the use to the devices it supports, see their website.
No, that is not the problem. I have 3 available slots and the problem persists,
Password not changed but Tidal suddenly stopped working, so it looks like a plugin issue.

**Comment by NielsMayer** [comment]
Please note that Strawberry Music Player (nee "Clementine" .... https://www.strawbs.org/ https://github.com/strawberrymusicplayer/strawberry ) continues to work with Tidal (and self-supplied app-token from my android filesystem :-) ) . This is perhaps due to Strawberry's support of OAUTH logins to Tidal.

Strawberry delivers MQA files (e.g. appearing as 48k/24 in linux and at non mqa DAC) as long as you login using the OAUTH option. It is very possible that the Kodi Tidal2 plugin was using non-OAUTH logins which perhaps got phased out recently. 
(I too received notification in email from Tidal to upgrade clients as I continue to use Kodi's Tidal plugin's superior functionality as long as I'm not trying to listen to "master" files).

I believe the use of non-OAUTH in this plugin is why it was only delivering 44.1k/16 FLAC files at best, even if the source was "master".

See also for tips/tricks/details https://forum.strawberrymusicplayer.org/topic/23/tidal-account/

**Comment by formidabilus** [comment]
> Please note that Strawberry Music Player (nee "Clementine" .... https://www.strawbs.org/ https://github.com/strawberrymusicplayer/strawberry ) continues to work with Tidal (and self-supplied app-token from my android filesystem :-) ) . This is perhaps due to Strawberry's support of OAUTH logins to Tidal.
> 
> Strawberry delivers MQA files (e.g. appearing as 48k/24 in linux and at non mqa DAC) as long as you login using the OAUTH option. It is very possible that the Kodi Tidal2 plugin was using non-OAUTH logins which perhaps got phased out recently.
> (I too received notification in email from Tidal to upgrade clients as I continue to use Kodi's Tidal plugin's superior functionality as long as I'm not trying to listen to "master" files).
> 
> I believe the use of non-OAUTH in this plugin is why it was only delivering 44.1k/16 FLAC files at best, even if the source was "master".
> 
> See also for tips/tricks/details https://forum.strawberrymusicplayer.org/topic/23/tidal-account/

Strawberry is cool because it can play MQA, but it sucks to use it because it doesn't have playlists and you need to search song by song to play it.

This problem with non-OAUTH and OAUTH was the same even before kodi19 and it still worked, I don't know what changed now that you can't login.

**Comment by fischcode** [comment]
Me, too, I received an e-Mail from Tidal following my unsuccessful login Hi,
It looks like you're using an older version of the TIDAL app on one or more of your devices.

Please update to the latest version of the app from your App Store on all your devices to continue listening to your favorite music. Please note that the TIDAL app only works on iOS 11 and higher. 

We regularly update the TIDAL app to improve your streaming experience. 
Please make sure you have the latest version on your devices to get the best listening experience.
Update Now

Thank you, 
TIDAL

**Comment by DMKell** [comment]
Same situation and same email from tidal

**Comment by klappspaten2** [comment]
Hi! Same issue for me, mail received and tidal not working anymore in Kodi.

**Comment by Bertl1976** [comment]
Same situation and same email from tidal

**Comment by fischcode** [comment]
Hi Arneson, hi everyone
I've managed to integrate the oauth login mechanism from morguldir's tidalapi (https://pypi.org/project/tidalapi/) and get the plugin back working:

[plugin.audio.tidal2-oauth.zip](https://github.com/arnesongit/plugin.audio.tidal2/files/6489220/plugin.audio.tidal2-oauth.zip)

Please note:
- Due to a dependendy on Python 3 concurrent.futures, this version only works with Python 3 and therefore Kodi 19
- When Logging in, Kodi displays a link that you have to open in an external browser to login. Remember to leave the Kodi dialog as soon as you have successfully copied the link.
- For the time being I've deactivated the mechanism to login using different sessions (morguldir's tidalapi only contains one working set of app credentials). 
- Using those app credentials, so far I only managed to get AAC, no FLAC. Still have to try with different app credentials.
@Arneson: Do you want to integrate these changes into your project? Should I do a branch?
Please let me know if you manage to install successfully :-)

**Comment by arneson** [comment]
@arnesongit

**Comment by thewoza** [comment]
> Hi Arneson, hi everyone
> I've managed to integrate the oauth login mechanism from morguldir's tidalapi (https://pypi.org/project/tidalapi/) and get the plugin back working:
> 
> [plugin.audio.tidal2-oauth.zip](https://github.com/arnesongit/plugin.audio.tidal2/files/6489220/plugin.audio.tidal2-oauth.zip)
> 
> Please note:
> 
> * Due to a dependendy on Python 3 concurrent.futures, this version only works with Python 3 and therefore Kodi 19
> * When Logging in, Kodi displays a link that you have to open in an external browser to login. Remember to leave the Kodi dialog as soon as you have successfully copied the link.
> * For the time being I've deactivated the mechanism to login using different sessions (morguldir's tidalapi only contains one working set of app credentials).
> * Using those app credentials, so far I only managed to get AAC, no FLAC. Still have to try with different app credentials.
> * Please let me know if you manage to install successfully :-)
> 
> @arneson: Do you want to integrate these changes into your project? Should I do a branch?

Great work, installed, logged in and verified working. Thank-you!

**Comment by fischcode** [comment]
> 
> 
> @arnesongit is the user you probably wanted to tag @fischcode :)

Thanks for the hint :-)

**Comment by arnesongit** [comment]
> Hi Arneson, hi everyone
> I've managed to integrate the oauth login mechanism from morguldir's tidalapi (https://pypi.org/project/tidalapi/) and get the plugin back working:
> 
> [plugin.audio.tidal2-oauth.zip](https://github.com/arnesongit/plugin.audio.tidal2/files/6489220/plugin.audio.tidal2-oauth.zip)
> 
> Please note:
> 
>     * Due to a dependendy on Python 3 concurrent.futures, this version only works with Python 3 and therefore Kodi 19
> 
>     * When Logging in, Kodi displays a link that you have to open in an external browser to login. Remember to leave the Kodi dialog as soon as you have successfully copied the link.
> 
>     * For the time being I've deactivated the mechanism to login using different sessions (morguldir's tidalapi only contains one working set of app credentials).
> 
>     * Using those app credentials, so far I only managed to get AAC, no FLAC. Still have to try with different app credentials.
> 
>     * Please let me know if you manage to install successfully :-)
> 
> 
> @arnesongit : Do you want to integrate these changes into your project? Should I do a branch?

Hi,
I allready integrated the OAuth login but I want to put it into github after I integrated some other stuff like Playlist Folders and Favorit Mixes.
In my version I used a ProgressDialog to wait for the Web-Logon so I don't use concurrent.futures. This version will run on Kodi 17-19 !

**Comment by fischcode** [comment]
> > Hi Arneson, hi everyone
> 
> > I've managed to integrate the oauth login mechanism from morguldir's tidalapi (https://pypi.org/project/tidalapi/) and get the plugin back working:
> 
> > 
> 
> > [plugin.audio.tidal2-oauth.zip](https://github.com/arnesongit/plugin.audio.tidal2/files/6489220/plugin.audio.tidal2-oauth.zip)
> 
> > 
> 
> > Please note:
> 
> > 
> 
> >     * Due to a dependendy on Python 3 concurrent.futures, this version only works with Python 3 and therefore Kodi 19
> 
> > 
> 
> >     * When Logging in, Kodi displays a link that you have to open in an external browser to login. Remember to leave the Kodi dialog as soon as you have successfully copied the link.
> 
> > 
> 
> >     * For the time being I've deactivated the mechanism to login using different sessions (morguldir's tidalapi only contains one working set of app credentials).
> 
> > 
> 
> >     * Using those app credentials, so far I only managed to get AAC, no FLAC. Still have to try with different app credentials.
> 
> > 
> 
> >     * Please let me know if you manage to install successfully :-)
> 
> > 
> 
> > 
> 
> > @arnesongit : Do you want to integrate these changes into your project? Should I do a branch?
> 
> 
> 
> Hi,
> 
> I allready integrated the OAuth login but I want to put it into github after I integrated some other stuff like Playlist Folders and Favorit Mixes.
> 
> In my version I used a ProgressDialog to wait for the Web-Logon so I don't use concurrent.futures. This version will run on Kodi 17-19 !
> 
> 
Hi Arnesongit
Looking forward to those improvements :-)

**Comment by hixaxon** [comment]
Hi,
could someone please help me find the Client Secret? I presume the Client ID is the X-Tidal-Token I've extracted from my android phone? Trying to run this plugin on Odroid n2 + coreelec.
Thank you.

**Comment by arnesongit** [comment]
> Hi,
> could someone please help me find the Client Secret? I presume the Client ID is the X-Tidal-Token I've extracted from my android phone? Trying to run this plugin on Odroid n2 + coreelec.
> Thank you.

https://forum.kodi.tv/showthread.php?tid=200555&pid=3039184#pid3039184

**Comment by hixaxon** [comment]
> > Hi,
> > could someone please help me find the Client Secret? I presume the Client ID is the X-Tidal-Token I've extracted from my android phone? Trying to run this plugin on Odroid n2 + coreelec.
> > Thank you.
> 
> https://forum.kodi.tv/showthread.php?tid=200555&pid=3039184#pid3039184

Thank you very much. Worked like a charm. I've used your web interface. :)

**Comment by formidabilus** [comment]
so it's back to square one? 

`Hi,

TIDAL changed the subscription types from Premium to HiFi and from HiFi to HiFi Plus.
Now with the HIFI subscription you can stream lossless ! And with HiFi Plus you can stream Hi-Res, Master Quality and Dolby Atmos.

And there is a new subscription type "Free" which should be available in the USA from the start and later for other countries.

I have to check the OAuth login method again. But I'm afraid that I loose my running streaming session ID which is active since several month ;-(

The best way to update/change Kodi versions is to make a backup of your settings.xml in the TIDAL2 userdata addon directory and restore it on the new Kodi.
Then you never lost your active session.

But I will try to fix the login problem.
It can be that the used API key of the Fire TV Stick which is the "NoDRM" version, is invalid now, so maybe it is not possible anymore to get a new "NoDRM" session.
Please cross your fingers that this is not the problem !

arneson`

**Comment by diegoflyer** [comment]
Dear all, not understand how to workaround to login...  not able to do after fresh intall...

**Comment by formidabilus** [comment]
> Dear all, not understand how to workaround to login... not able to do after fresh intall...

You can't right now, there is a need to find a new API key set.

**Comment by formidabilus** [comment]
search on google "apikey.py tidal", first result should be a github page of "yaronzz", navigate on the page to Tidal-Media-Downloader/TIDALDL-PY/tidal-dl/apiKey.py and from that file copy one by one the clientId and clientSecret from "platform": "Android Auto" in your Tidal app settings from Kodi. Logoff and login again in tidal app and it should work for now.

**Comment by WohnW** [comment]
> search on google "apikey.py tidal", first result should be a github page of "yaronzz", navigate on the page to Tidal-Media-Downloader/TIDALDL-PY/tidal-dl/apiKey.py and from that file copy one by one the clientId and clientSecret from "platform": "Android Auto" in your Tidal app settings from Kodi. Logoff and login again in tidal app and it should work for now.

Dear @formidabilus  - could you please ellaborate more step by step how to make it? Perhaps I am dumb but don't understand  how to "(...)and from that file copy one by one the clientId and clientSecret from "platform": "Android Auto" in your Tidal app settings from Kodi"

**Comment by WohnW** [comment]
Lovely!!!
Worked for me!!
Thank You!

W dniu 14.02.2022 o 17:40, Razvan Chiriac pisze:
