### ISSUE TITLE
Forbidden - Client not found

### ISSUE THREAD

**Issue by hixaxon** [arnesongit/plugin.audio.tidal2#29]
Hello Arneson,

Is there or do you think there might be a way how to use your (awesome, btw) plugin with the changes to the login procedure? Currently getting the "Client not found" and "Forbidden" messages for all preset Tokens (as others, apparently).

I'm not a programmer, but would it be useful, for example, to import my own access token somewhere into your plugin? This procedure seems doable. https://yaronzz.top/post/get_accesstoken/

Or there is no hope and we all need to switch from kodi to a proprietary streamer device? 

Thank you and have a nice day,
hix.

**Comment by arnesongit** [comment]
Use clientId and clientSecret from [here](https://github.com/yaronzz/Tidal-Media-Downloader/blob/master/TIDALDL-PY/tidal_dl/tidal.py)
