### ISSUE TITLE
Respect TIDAL Sorting

### ISSUE THREAD

**Issue by luzik** [arnesongit/plugin.audio.tidal2#3]
I can sort MyMusic Tracks A-Z or Z-A but can't do it as TIDALv1, native iPhone app or native TIDAL web interface. This is especially problem in Artist top tracks because they are sorted in right way and TIDALv2 broke this

**Comment by omenek159** [comment]
It was big problem for me too, but eventually I changed some code on my own and now it sort songs by date. I don't know Python at all but using my knowledge I was able to acomplish what I wanted. 

I had to change code in two places:
1. resources/lib/tidal2/tidalapi/\_\_init\_\_.py around line 492:
 ```
elif 'item' in item:
    cutData = item.get('cut', None)
    creationDate = item['created'] # get creation date for item
    item = item['item']
    item['created'] = creationDate # append creation date at the end
```
2. resources/lib/tidal2/main.py around line 769:
```
else:
    items.sort(key=lambda line: line.created, reverse=True) # change the way it sorts songs
add_items(items, content=CONTENT_FOR_TYPE.get(content_type, 'songs'), withNextPage=True)
```
