### ISSUE TITLE
only 30 sec for song

### ISSUE THREAD

**Issue by FPSCD** [arnesongit/plugin.audio.tidal2#32]
I do not know what goes wrong,  but on a Pi 3b with Hifiberry Dac+ I only get 30 sec of each song, and the sound's quality is mp3. Member of Tidal cat premium

**Comment by kevin-garcia** [comment]
I'm having the same issue on an Odroid N2+. I'm only getting 30 seconds of each song. Not sure what the sound quality is, but I'm on a HiFi subscription.

**Comment by arnesongit** [comment]
You're not logged in successfully. Without login the items are played in "preview" mode with low quality and 30 seconds.
