### ISSUE TITLE
Does Music quality option mismatch

### ISSUE THREAD

**Issue by kec2** [arnesongit/plugin.audio.tidal2#36]
I'm wondering if the Music Quality options make sense since Tidal has abandoned MQA?

The mobile and web app only have three options: 
Low (96/320 kbps)
High (16bit, 44.1 kHz)
Max (Up to 24bit, 192 kHz)

**Comment by arnesongit** [comment]
TIDAL uses Low/Max/High in its player, but the API has 4 Quality levels.
Low (96 kbps)
High (320 kbps)
Lossless (16 bit FLAC, 44.1 or 48 kHz)
HiRes (24 bit, up to 192 kHz)
