### ISSUE TITLE
[Request] Add option to disable any type of OSD info

### ISSUE THREAD

**Issue by ronnocnave** [arnesongit/plugin.audio.tidal2#38]
When listening to music on various skins, the Tidal add-on adds some basic text on the OSD that clash with the Music OSD of the skin in use. Can there be a config option to disable this? I can provide screenshots on request.

**Comment by ronnocnave** [comment]
BTW I'm just using the default Skin, I wouldn't expect an ad-don to try to cater to any random skin out there. Just to further clarify, the add-on shows artist / title info that's already present on the screen with the now-playing view anyway. And it overlaps and looks rather clunky. Again, I can provide screenshots on request. Thank you.

**Comment by arnesongit** [comment]
Did you try to disable the option "Set playback information for Web-GUI" ?
The option is for the Web-Frontend of Kodi. If this is not set, the Web-UI will only show the internal track IDs for the items.

**Comment by ronnocnave** [comment]
It appears to be a skin issue, this can be closed. Thanks for the feedback and the excellent add-on.
