### ISSUE TITLE
Support for Kodi 21

### ISSUE THREAD

**Issue by maninalift** [arnesongit/plugin.audio.tidal2#39]
Does this plugin support Kodi 21? 

I am on Kodi 21.1, when I attempt to install this addon I get the following error:

```
  [script.module.routing](https://mirrors.kodi.tv/addons/matrix/script.module.routing/script.module.routing-0.2.3+matrix.1.zip)
```

I notice that the readme only mentions versions 17, 18 , 19 and 20 (I used the zip file for version 19 and 20 https://github.com/arnesongit/repository.tidal2/blob/main/plugin.audio.tidal2/plugin.audio.tidal2-2.1.5.zip

**Comment by arnesongit** [comment]
Yes, the addon supports Kodi 21.1. I'm using it on macOS, Linux and Windows on Kodi 21.1 and I have no problems.
It is possible that your Kodi has an old version of the routing addon in its cache.
Pleas try to update it, for instance from here: https://mirrors.kodi.tv/addons/omega/script.module.routing/script.module.routing-0.2.3+matrix.1.zip
You can see, that the omega version has the same version number. Your routing addon seems to be the one for matrix.

**Comment by maninalift** [comment]
> Yes, the addon supports Kodi 21.1. I'm using it on macOS, Linux and Windows on Kodi 21.1 and I have no problems.
> It is possible that your Kodi has an old version of the routing addon in its cache.
> Pleas try to update

Thank you. I'll try that

**Comment by prm680528** [comment]
why does kodi exist when it not support dvd .iso ?????
