### ISSUE TITLE
gapless playback

### ISSUE THREAD

**Issue by Tecko71** [arnesongit/plugin.audio.tidal2#5]
Gapless playback does not work in Tidal2. I added crossfade but  that is only  working with local library.

**Comment by arnesongit** [comment]
I don't have problems with gapless playback on macOS and Linux/LibreELEC on an Intel NUC.
It may be a problem with slow ARM devices running Android (interpreted Java apps on Linux) and Kodi which has a "Python interpreter". For a smooth Kodi system you need a more performant hardware and Kodi running natively on the operating system.

**Comment by Tecko71** [comment]
Kodi for me is only usefull when running on nvidia shield as a media centre.

**Comment by Tecko71** [comment]
Pitty that gapless is not working for nvidia shield with tidal. It is working for the local library. Still do not understand it why it is a issue for Tidal plugin

**Comment by arnesongit** [comment]
On macOS and LibreELEC on my Intel NUC I don't have problems with gapless playback. And I don't use any gapless playback addon or setting because this causes a "resampling" of the complete audio data. This destoys the quality of the native audio stream and MQA can't be decoded anymore.
Please try to disable all gapless and resampling settings. Choose "Best match" for the audio output configuration and disable "Stereo Upmix". I also disabled the "Volume adjustment" because the TIDAL streams contain "replay gain" settings. This also causes "resampling".
For better network performance I added some buffering settings in the advancedsettings.xml
see here: https://kodi.wiki/view/Advancedsettings.xml
I'm using this settings:
&lt;?xml version="1.0" encoding="UTF-8"?>
&lt;advancedsettings>
  &lt;cache>
    &lt;memorysize>104857600&lt;/memorysize>
    &lt;buffermode>1&lt;/buffermode>
    &lt;readfactor>4.0&lt;/readfactor>
  &lt;/cache>
&lt;/advancedsettings>

**Comment by arnesongit** [comment]
For gapless problems there are some posts in the TIDAL2 Kodi forum.
Perhaps you can find an answer there:
https://forum.kodi.tv/showthread.php?tid=200555&pid=2691922&highlight=gapless+stream#pid2691922

**Comment by Tecko71** [comment]
I tried differend settings no luck, i used djay themes. And one time youre settings. It is pitty because through kodi Tidal sounds better than the Tidal androidTV app.

**Comment by arnesongit** [comment]
I think I can't help you with your problem. The TIDAL2 addon delivers the playback URLs to the Kodi play engine it it requests this URL. And if a song play the next URL is requested 5 seconds before the song ends.
I've no idea where the gapless playback issue on android come from.

**Comment by Tecko71** [comment]
thx for the support. Can I log tidal addon to figure out where it cames from?

**Comment by Tecko71** [comment]
I find the log file 
[kodi.log](https://github.com/arnesongit/plugin.audio.tidal2/files/9578467/kodi.log)

**Comment by Tecko71** [comment]
I installed kodi leia 18.9 and when I turning on there crossfade 5 seconds,  I have gapless playback. So something in Matrix (19.4) is not working the right way.

**Comment by Tecko71** [comment]
Think I find the right setting: Kopied it from Leia defaults. I put playbac flac MPD to Play as HLS. Crossfade 5 seconds then I have gapless

**Comment by arnesongit** [comment]
I think the crossfase function will only work with the audio playback engine in Kodi, which is called PAPlayer. Using the inputsteam addons the VideoPlayer engine is used (look into your log file !).
"Normal" HTTPS streaming with FLAC codec should also use the PAPlayer. With the MPD-to-HLS converter your Kodi box seems to use the PAPlayer. If this is ok for you, you can use it in this way, but the fast-forward function will not work.
You can also try to use a Client-ID type which uses HTTPS steaming for everything, like "Automotive".
I'm using the device type "TV Non Drm Dolby Atmos" from the TIDAL apk version 2.36.2. This one streams everyting in HTTPS and the access tokens expires every 7 days and not every 24 hours like with the newer device types !
Please check your kodi.log if the HTTPS streams are played with the PAPlayer.
If not, you can force the PAPlayer with the payercorefactory.xml like this:
&lt;?xml version="1.0" encoding="UTF-8"?>
&lt;playercorefactory>
  &lt;rules name="system rules">
    &lt;rule name="streams" internetstream="true">
      &lt;rule name="tidal2flac" mimetypes="audio/flac|audio/x-flac" filetypes="flac" player="PAPlayer" />
    &lt;/rule>
  &lt;/rules>
&lt;/playercorefactory>

**Comment by Tecko71** [comment]
I do not get it running on 19.4 anymore (crossfade). So back to Leia 18.9. Also I tried different apk version. For Leia tidal 2.36.2 apk works best. Then everything works as it supose to be working.

**Comment by jbrepogmailcom** [comment]
> I think I can't help you with your problem. The TIDAL2 addon delivers the playback URLs to the Kodi play engine it it requests this URL. And if a song play the next URL is requested 5 seconds before the song ends. I've no idea where the gapless playback issue on android come from.

Hello I think in my KODI 18 the player does not request URL 5 seconds in advance. Is there any way how to check? I have enabled debug and audio in log but I do not see any requests from player before end of current song

**Comment by Tecko71** [comment]
I installed now kodi on Shield android TV. It is pitty that gapless playback still does not work because the kodi tidal2 plugin is much better than Tidals app.

**Comment by arnesongit** [comment]
Because Android is a Linux platform the inputstream.ffmpegdirect can't play MPD (Mpeg Dash) streams.
The best way ist to use an "automotive" device type because these device types use plain HTTP streaming.
And you have to disable the setting "Use inputstream.ffmpegdirect as default player" in the TIDAL2 addon settings.
see here:
https://forum.kodi.tv/showthread.php?tid=200555&pid=3121636#pid3121636
https://forum.kodi.tv/showthread.php?tid=200555&pid=2691922#pid2691922

**Comment by Tecko71** [comment]
I did follow this instructions. But when I disable inputstream.ffmpegdirect as default player than the gapless is working but when starting the next song the music stops playing (round 19seconds). 

update:
I ve got it working, Do use version 2.36.2 apk and selected : Tv Non Drm Dolby Atmos  , automotive etc did not work

**Comment by Uukrull** [comment]
> update: I ve got it working, Do use version 2.36.2 apk and selected : Tv Non Drm Dolby Atmos , automotive etc did not work

Thanks for that info. Gapless playback working flawlessly on my Windows machine and on my Shield TV.
