### ISSUE TITLE
Add to library 

### ISSUE THREAD

**Issue by rapteev** [arnesongit/plugin.audio.tidal2#6]
I would love to see implemented an option for add artists/albums to kodi library.
 Thanks

**Comment by arnesongit** [comment]
I tried to make a "fake" library with artist.nfo and album.nfo files but they arne not imported to the music library because the music files are missing. Then I tried to make .strm files for the streams. This .strm files can be played with kodi in file mode but they arne not detected as music files. the ".strm" files are reserver for video streams and not for music.
So there is no method to import addon stream urls to the kodi music library, sorry.

**Comment by smoothquark** [comment]
Thank you for this plugin - it is working very well with with Nvidia Shield. I have been trying to integrate Tidal into my library too. I have actually had some success using a modified version of TIDAL Fuse (https://github.com/bjesus/tidalfs), symbolic links to the fuse filesystem and custom album.nfo and album.cue files. It is the album.cue that seems to be crucial for the Kodi generic album scanner to populate the database. It is rather convoluted and currently requiring multiple scripts, so not sure if this will be a viable project for me. However, perhaps there may be a way to create a "virtual library" by creating links from a folder with suitable album.nfo and album.cue files? Happy to post my test album.nfo and album.cue if anyone is interested.

**Comment by ntinetwork** [comment]
Hi smoothquark
I’m very interested if you could post the test album.nfo and album.cue.
I do not have enough skills to help develop this but maybe arnesongit can help. Some time ago he also tried this

**Comment by smoothquark** [comment]
I have attached the album.nfo and album.cue for my testing with Beyonce's RENAISSANCE album (Tidal ID: 257919643, MBID: 0ea7f4ea-abb6-41a4-bc6a-876792ecacff). Not all the tracks are listed as I have only been testing. This is the Dolby Atmos album, so the links are to .m4a. I have also been testing with Beck's Sea Change with .mpd files. Both play on Kodi on my Debian Bookworm desktop. I think the MB id is mandatory, so I am currently trying to find a way to map albums on Tidal with a suitable MusicBrainz id that I can use. Hopefully, it is helpful to someone...

[album-Beyonce-RENAISSANCE.zip](https://github.com/user-attachments/files/17269113/album-Beyonce-RENAISSANCE.zip)
