### ISSUE TITLE
Requested quality is not allowed in user's subscription

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [arnesongit/plugin.audio.tidal2#7]
When I try to play a song with the addon, all I get is 

> 401: Requested quality is not allowed in user's subscription

I have a Hifi Subscription, but it does not really matter what kind of quality I'm trying to play.
Visiting the API Url from the Kodi.log file says

`{"status":401,"subStatus":6005,"userMessage":"Missing sessionId"}`

Maybe the api has been changed?

**Comment by arnesongit** [comment]
The error is "Missing sessionId". It seems that the login failed. Please try to logout and login again.
Is the subscription type correctly set in the Addon Settings ?
If this fails, please delete the "Unique Client Key" from the Settings and try again.
