### ISSUE TITLE
Play using Kore sharing feature

### ISSUE THREAD

**Issue by quentinus95** [arnesongit/plugin.audio.tidal2#7]
Hi, I'm using Kore to interact with my Kodi instance. Today, when you use the share feature of an Android phone, you can pick Play on Kodi and Queue on Kodi.

It would be awesome to have it being picked by the Tidal plugin (no idea if it is possible). This way we can use the Tidal Android app that has a nice UX to pick an Artist / Playlist / Song and queue it on Kodi.

Thanks for your work on this plugin, by the way!

**Comment by arnesongit** [comment]
Sorry, there is no way to interact between the original TIDAL android app and the Kodi TIDAL2 addon.

**Comment by quentinus95** [comment]
Hi @arnesongit, thanks for your answer! So the idea would _not_ to get the Tidal Android app and the plug-in to work together.
Insead, the idea would be, when you use the share feature from Tidal Android and choose Kore, to have your plug-in pick the shared link and start playing.

It is already working with YouTube and the YouTube plugin; you share a Youtube link to Kore and magic happens.

So you believe it would be achievable with your plug-in?

Thanks a lot!

**Comment by arnesongit** [comment]
Ok, I will try this out.

**Comment by arnesongit** [comment]
This runs only with the plugin.video.sendtokodi addon and this addon grabs the playback url with its own "extractors".
When I share a song in tha TIDAL with the KORE app an url like "https://tidal.com/browse/track/1414141". This can't be played directly and the plugin.video.sendtokodi addon can't be extended from outside.
Android is not my target platform and the SendToKodi app for IOS is complicated to use. Then it bill be easier to use the web frontend of Kodi to browse through the TIDAL2 content.

**Comment by quentinus95** [comment]
Thanks for giving a try!
