### ISSUE TITLE
MQA or Atmos labels

### ISSUE THREAD

**Issue by luckylukz02** [arnesongit/plugin.audio.tidal2#8]
Can't see any MQA or Atmos labels

Do you have any examples of this?

**Comment by arnesongit** [comment]
Is "Add MQA or Atmos to Labels" enabled in the addon settings ?

**Comment by luckylukz02** [comment]
> Is "Add MQA or Atmos to Labels" enabled in the addon settings ?

Yes

**Comment by arnesongit** [comment]
Which Kodi skin do you use ?
I tried the default skin and Confluence which I prefer. I have MQA and Atmos in the labels.
If you mean the Album item/song list, you're right. This view doesn't show the labels which the TIDAL2 addon sets to the items. It shows the track number and the song name for each item.

**Comment by luckylukz02** [comment]
I tried the default skin and yes it does show the labels.

I am currently using Arctic Horizon 2.
